apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: nginx
spec:
  replicas: 2

  selector:
    matchLabels:
      app: notes-app

  template:
    metadata:
      labels:
        app: notes-app

    spec:
      containers:
        - name: notes-app

          image: sagarendure/notes-app:latest

          imagePullPolicy: Always

          ports:
            - containerPort:  8000
          env:
            - name: DB_NAME
              value: "test_db"

            - name: DB_USER
              value: "root"

            - name: DB_PASSWORD
              value: "root"

            - name: DB_HOST
              value: "mysql-service"

            - name: DB_PORT
              value: "3306"
